### ISSUE TITLE
Not working under Kali (last ver)

### ISSUE THREAD

**Issue by donvitoz** [R3dy/ciscobruter#2]
...............
...............
...............
Installing celluloid 0.17.3
Bundle complete! 4 Gemfile dependencies, 15 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
root@kali:/usr/share/ciscobruter# ./ciscobruter.rb 
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- thread/pool (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./ciscobruter.rb:6:in `<main>'
root@kali:/usr/share/ciscobruter# ./ciscobruter.rb -h
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- thread/pool (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./ciscobruter.rb:6:in `<main>'
root@kali:/usr/share/ciscobruter#

**Comment by R3dy** [comment]
looks like the thread gem isn't loading properly.  Should be fixed with the recommendation in #1

**Comment by R3dy** [comment]
Closing for lack of response from @donvitoz

**Comment by R3dy** [comment]
Closing for lack of response from @donvitoz
